Repository Bibumhada/todays-menu-front, pull requests merged in 2023-09, with the labels that each got.

#9 추천 페이지 공통 컴포넌트 구현
  .eslintrc
  .eslintrc.js
  .prettierrc
  src/App.tsx
  src/assets/images/.gitkeep
  src/assets/images/btn-retry.svg
  src/components/common/MenuCard/MenuCard.styled.ts
  src/components/common/MenuCard/MenuCard.tsx
  src/components/common/button/button.styled.ts
  src/components/common/button/button.tsx
  src/pages/Landing/Landing.styled.tsx
  src/pages/Landing/Landing.tsx
  src/pages/Location/Location.tsx
  src/pages/RandomList/RandomList.tsx
  src/pages/Result/Result.tsx
  src/pages/Vote.tsx
  src/pages/Vote/Vote.styled.ts
  src/pages/Vote/Vote.tsx
  src/router/.gitkeep
  src/router/AppRoutes.tsx
  src/styles/GlobalStyle.js
Labels: 마크업 & 스타일링

#12 로딩 중 페이지 UI 구현, min-width 추가, 절대경로로 시작하도록 tsconfig 수정
  src/assets/images/bg-loading.svg
  src/assets/images/gray-dot.svg
  src/assets/images/icon-hamburger.svg
  src/assets/images/icon-noodle.svg
  src/assets/images/icon-sandwich.svg
  src/assets/images/icon-soup.svg
  src/assets/images/icon-sushi.svg
  src/pages/Loading/Loading.styled.tsx
  src/pages/Loading/Loading.tsx
  src/pages/Location/Location.tsx
  src/router/AppRoutes.tsx
  src/styles/GlobalStyle.js
  tsconfig.json
Labels: 마크업 & 스타일링

#20 RandomList json server로 테스트 suspense와 react query 사용
  .eslintrc
  package.json
  src/App.tsx
  src/apis/api/getAddressAPI.tsx
  src/apis/api/getAddressApi.tsx
  src/apis/api/getRandomListAPI.tsx
  src/apis/api/getRandomListApi.tsx
  src/apis/base/instance.ts
  src/apis/query/useGetRandomList.tsx
  src/components/common/AsyncBoundary.tsx
  src/components/common/MenuCard/MenuCard.styled.ts
  src/components/common/MenuCard/MenuCard.tsx
  src/index.tsx
  src/mock/expectedResponse.json
  src/pages/Loading/Loading.styled.tsx
  src/pages/Loading/Loading.tsx
  src/pages/Location/Location.tsx
  src/pages/RandomList/RandomList.tsx
  src/pages/Vote/Vote.tsx
  src/router/AppRoutes.tsx
  src/util/splitCategory.tsx
  yarn.lock
Labels: 버그, 개발환경 세팅, 기능 구현

#22 RandomList페이지 UI, assets icons, images 폴더 분리, 루트 layout Height값 삭제
  src/assets/icons/btn-change.svg
  src/assets/icons/btn-getLocation.svg
  src/assets/icons/btn-link.svg
  src/assets/icons/btn-retry.svg
  src/assets/icons/gray-dot.svg
  src/assets/icons/icon-hamburger.svg
  src/assets/icons/icon-kakaotalk.svg
  src/assets/icons/icon-noodle.svg
  src/assets/icons/icon-sandwich.svg
  src/assets/icons/icon-share-link.svg
  src/assets/icons/icon-soup.svg
  src/assets/icons/icon-sushi.svg
  src/assets/icons/icon-yummy.svg
  src/assets/images/background-top.png
  src/components/common/Button/Button.styled.ts
  src/components/common/Button/Button.tsx
  src/components/common/MenuCard/MenuCard.styled.ts
  src/components/common/MenuCard/MenuCard.tsx
  src/pages/Loading/Loading.styled.tsx
  src/pages/Loading/Loading.tsx
  src/pages/Location/Location.styled.ts
  src/pages/RandomList/RandomList.styled.tsx
  src/pages/RandomList/RandomList.tsx
  src/pages/Vote/Vote.tsx
  src/styles/AppLayout.jsx
  src/styles/GlobalStyle.js
Labels: 버그, 개발환경 세팅, 기능 구현

#26 OverallRanking 페이지 생성 및 디자인 구현
  package.json
  src/assets/icons/btn-link-gray.svg
  src/assets/icons/icon-share-resut.svg
  src/assets/icons/icon-winner.svg
  src/components/common/modal/ShareBottomSheet.styled.ts
  src/components/common/modal/ShareBottomSheet.tsx
  src/pages/OverallRanking/OverallRanking.styled.ts
  src/pages/OverallRanking/OverallRanking.tsx
  src/pages/Result/Result.styled.ts
  src/pages/Result/Result.tsx
  src/pages/Vote/Vote.tsx
  src/router/AppRoutes.tsx
  yarn.lock
Labels: 마크업 & 스타일링

#28 OverallRanking 페이지 API 연결
  package.json
  src/App.tsx
  src/apis/api/getRandomListApi.tsx
  src/apis/api/getResult.tsx
  src/apis/base/instance.ts
  src/apis/query/useGetRandomList.tsx
  src/apis/query/useGetResult.tsx
  src/components/common/AsyncBoundary.tsx
  src/pages/OverallRanking/OverallRanking.styled.ts
  src/pages/OverallRanking/OverallRanking.tsx
  src/pages/RandomList/RandomList.tsx
  yarn.lock
Labels: 개발환경 세팅, 기능 구현

#31 29 [Frontend] Feat: Result 페이지 API 연결
  src/apis/query/useGetResult.tsx
  src/assets/icons/icon-retry-orange.svg
  src/assets/icons/icon-to-detail-black.svg
  src/components/common/ResultCard/ResultCard.styled.ts
  src/components/common/ResultCard/ResultCard.tsx
  src/pages/OverallRanking/OverallRanking.tsx
  src/pages/Result/Result.styled.ts
  src/pages/Result/Result.tsx
Labels: 마크업 & 스타일링, 기능 구현

#43 결과 페이지 서버 API 연결
  src/apis/api/getResult.tsx
  src/apis/base/instance.ts
  src/apis/query/useGetResult.tsx
  src/components/common/ResultCard/ResultCard.styled.ts
  src/components/common/ResultCard/ResultCard.tsx
  src/pages/OverallRanking/OverallRanking.styled.ts
  src/pages/OverallRanking/OverallRanking.tsx
  src/pages/Result/Result.tsx
Labels: 개발환경 세팅, 기능 구현

#48 결과페이지 식당 이름 긴 경우 디자인 수정
  public/index.html
  src/components/common/ResultCard/ResultCard.styled.ts
  src/components/common/ResultCard/ResultCard.tsx
  src/components/common/modal/ShareBottomSheet.tsx
  src/pages/OverallRanking/OverallRanking.styled.ts
  src/pages/OverallRanking/OverallRanking.tsx
Labels: 마크업 & 스타일링

#49 동적으로 roomId 받아오기 및 전체 페이지 연결, 로딩중 및 에러 페이지 연결
  src/components/common/ResultCard/ResultCard.tsx
  src/pages/OverallRanking/OverallRanking.tsx
  src/pages/Poll/Poll.tsx
  src/pages/RandomList/RandomList.tsx
  src/pages/Result/Result.tsx
Labels: 기능 구현
